### ISSUE TITLE
Broken RSS feed link

### ISSUE THREAD

**Issue by kotatsuyaki** [kazanV/kazanV.github.io#7]
The RSS feed icon button in the top-right corner leads to GitHub's 404 page.  According to [the readme of the Landscape theme][landscape-readme], the [hexo-generator-feed] plugin is required.

[landscape-readme]: https://github.com/hexojs/hexo-theme-landscape/blob/7dfe38c6e50b98ad63c51e24cca3f1caf8714870/README.md
[hexo-generator-feed]: https://github.com/hexojs/hexo-generator-feed

**Comment by kazanTW** [comment]
Thx. I've resolved this with [commit b38b473](https://github.com/kazanV/kazanV.github.io/commit/b38b4732595e52205221c8137901e22bcdc429c6).
